stages:
  - check
  - docker-build
  - build
  - publish
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  GIT_SUBMODULE_STRATEGY: recursive

check-dco:
  stage: check
  image: docker:latest
  script:
    - apk update && apk add python3 git
    - chmod +x .gitlab-ci.d/check-dco.py
    - .gitlab-ci.d/check-dco.py
  variables:
    GIT_DEPTH: 1000

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - pwd
    - df -h
    - docker volume ls
    - echo $PWD
    - ls -al
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - DATE=`date '+%Y%m%d'`
    - docker images
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$DATE || true
    - docker images
    - docker build --cache-from $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$DATE --tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$DATE .
    - docker images
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$DATE
    - docker tag  $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$DATE  $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker container ls -a
    - df -h




build:
  stage: build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - df -h
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - DATE=`date '+%Y%m%d'`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - ls
    - rm -rf build_ci/*
    - df -h
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DNESTC_WITH_EVTA=ON -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_WITH_BUNDLES=ON"
    - docker exec build sh -c "cd build_ci; cat ../nestc_tests/nestc_vta_bundle_tests.txt | xargs -I {} ninja {}"
    - docker exec build sh -c "cd build_ci; cat ../nestc_tests/nestc_build_tests.txt | xargs -I {} ninja {}"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja tvm"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja check_nestc"
    - du -h -d 1
  tags:
    - etri

build_from_aws:
  stage: build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - df -h
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - DATE=`date '+%Y%m%d'`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - ls
    - rm -rf build_ci/*
    - df -h
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DNESTC_WITH_EVTA=ON -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_WITH_BUNDLES=ON -DNESTC_USE_PRECOMPILED_BUNDLE=ON -DNESTC_USE_PRECOMPILED_BUNDLE_FROM_AWS=ONs"
    - docker exec build sh -c "cd build_ci; cat ../nestc_tests/nestc_vta_bundle_tests.txt | xargs -I {} ninja {}"
    - docker exec build sh -c "cd build_ci; cat ../nestc_tests/nestc_build_tests.txt | xargs -I {} ninja {}"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja tvm"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja check_nestc"
    - du -h -d 1
  tags:
    - etri

build-publish:
  stage: build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - PWD=`pwd`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - rm -rf build_ci/*
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DNESTC_WITH_EVTA=ON -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_WITH_BUNDLES=ON -DNESTC_OPENCL_TEST=ON -DNESTC_RELAY_TARGET_MALI=ON -DNESTC_TARGET_AARCH64=ON"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja vtaMxnetResnet18Bundle"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja resnet18RelayOpenCLBundleCPPGen"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja resnet18RelayAarch64BundleCPPGen"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja vtaMxnetResnet18PartitionBundleNet"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja vtaMxnetResnet18RelayEVTAPartitionBundleCPPGen"
  artifacts:
    paths:
      - build_ci/vta/bundles
      - build_ci/examples
  tags:
    - etri


build-multievta:
  stage: build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - df -h
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - DATE=`date '+%Y%m%d'`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - ls
    - rm -rf build_ci/*
    - df -h
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DNESTC_WITH_EVTA=ON -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_WITH_BUNDLES=ON -DNESTC_EVTA_MULTI=ON"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja check_multievta"
    - du -h -d 1
  tags:
    - etri


build-vtaconv:
  stage: build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - df -h
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - DATE=`date '+%Y%m%d'`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - ls
    - rm -rf build_ci/*
    - df -h
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DNESTC_WITH_EVTA=ON -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_WITH_BUNDLES=ON -DNESTC_EVTA_GRAPH_OPT=ON"
    - docker exec build sh -c "cd build_ci; cat ../nestc_tests/nestc_vta_bundle_tests.txt | xargs -I {} ninja {}"
    - docker exec build sh -c "cd build_ci; cat ../nestc_tests/nestc_build_tests.txt | xargs -I {} ninja {}"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja check_nestc"
    - du -h -d 1
  tags:
    - etri


build-debug:
  stage: build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - df -h
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - DATE=`date '+%Y%m%d'`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - ls
    - rm -rf build_ci/*
    - df -h
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Debug -DGLOW_WITH_BUNDLES=ON -DNESTC_WITH_EVTA=ON -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_VTA_INTERPRETER_FUSION=ON -DGLOW_VTA_FUSION=ON"
    - docker exec build sh -c "cd build_ci; cat ../nestc_tests/nestc_build_tests.txt | xargs -I {} ninja {}"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja tvm"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja check_nestc"
    - du -h -d 1
  tags:
    - etri




build-without-VTA:
  stage: build
  image: docker:latest
  services:
    - docker:18.09.7-dind
  script:
    - df -h
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - DATE=`date '+%Y%m%d'`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - ls
    - rm -rf build_ci/*
    - df -h
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DGLOW_WITH_BUNDLES=ON"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja all;"
    - du -h -d 1
  tags:
    - etri



build-all:
  stage: build
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - df -h
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - DATE=`date '+%Y%m%d'`
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - docker images
    - docker volume ls
    - docker ps -a
    - cd ../../
    - mkdir -p build_ci
    - ls
    - rm -rf build_ci/*
    - df -h
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker volume ls
    - docker ps -a
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; rm -rf *; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_WITH_BUNDLES=ON -DNESTC_WITH_EVTA=ON -DGLOW_WITH_STC=ON"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja all;"
    - du -h -d 1
  tags:
    - etri


test-all:
  stage: test
  image: docker:latest
  services:
    #    - docker:19.03.7-dind
    - docker:18.09.7-dind
  #    - docker:dind
  script:
    - PWD=`pwd`
    - echo $PWD
    - ls -al
    - cd utils/docker
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest || true
    - cd ../../
    - mkdir -p build_ci
    - docker create --name build -i -v $PWD:/root/dev $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    - docker start build
    - docker exec build sh -c "ls;cd build_ci; cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DGLOW_WITH_BUNDLES=ON -DGLOW_WITH_VTA=ON -DGLOW_WITH_STC=ON"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja all;"
    - docker exec build sh -c ". /root/dev/utils/docker/ev.txt; cd build_ci; ninja check"
  when: manual
  allow_failure: true
  tags:
    - etri


publish:
  stage: publish
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - aws configure set region  ap-northeast-2
    - aws s3 rm s3://$S3_BUCKET/ --recursive
    - aws s3 cp build_ci s3://$S3_BUCKET/ --recursive
  when: manual
  allow_failure: true