stages:
  # - check
  - build
  - publish
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 1000

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

# check-dco:
#   stage: check
#   image: onesai1/dco-check:latest
#   script:
#     - check-dco

.builds:
  stage: build
  image: onesai1/nest-compiler-sdk:1.0.0
  before_script:
    - echo $CI_PROJECT_DIR
    - pwd
    - ls -al
    - mkdir build_ci
    - cd build_ci
    - export TVM_HOME=$CI_PROJECT_DIR/tvm
    - export DMLC_CORE=$CI_PROJECT_DIR/tvm/3rdparty/dmlc-core
    - export TVM_BUILD_PATH=$CI_PROJECT_DIR/build_ci/tvm
    - export TVM_LIBRARY_PATH=$CI_PROJECT_DIR/build_ci/tvm
    - export PATH=$CI_PROJECT_DIR/build_ci/tvm:$PATH
    - export PYTHONPATH=$TVM_HOME/python:$PYTHONPATH
  tags:
    - etri-compute

build-mnist:
  extends: .builds
  script:
    - cmake -G Ninja ../ -DCMAKE_BUILD_TYPE=Release -DNESTC_WITH_EVTA=OFF -DNESTC_EVTA_BUNDLE_TEST=ON -DGLOW_WITH_BUNDLES=ON
    - ninja QuantizedLeNetMnistBundleNet
    - ./glow/bundles/quantized_lenet_mnist/QuantizedLeNetMnistBundle ../nest-compiler/glow/tests/images/mnist/5_1087.png
    - ls ../ -al
    - ls -al


